# docker-compose.yaml define and configure the "network of services" (containers)
services:
    # web server: nginx
    web:
        image: nginx:latest
        ports:
            - "80:80" # first is the local machine, second is port from container
        volumes:
            - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/html/public
    # php
    app:
        build:
            dockerfile: Dockerfile
        volumes:
#            - /var/www/html/vendor  # protect this location inside container (don't overwrite it)
            - ./:/var/www/html
            - ./.docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro # ro = read only
        environment:
            # See https://xdebug.org/docs/all_settings#mode
            XDEBUG_MODE: "${XDEBUG_MODE:-debug}"
        extra_hosts:
            # Ensure that host.docker.internal is correctly defined on Linux
            - host.docker.internal:host-gateway
    # mysql
    db:
        image: mysql:8.0
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - "3306:3306" # first is the local machine, second is port from container
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_DATABASE: docker-php
    # redis
#    cache:
#        image: redis:latest
volumes:
    mysqldata: